### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bits-service#1]
Repo was mentioned in Feb 2016 CAB meeting notes but neither it nor this repo says what bits-service is.

**Comment by smoser-ibm** [comment]
Hey Nic, 

the bits-service incubation has been already proposed some time ago via 
cf-dev. In short, the "bits service" is basically a service that will take 
bits (packages, droplets, etc) and provide upload/download capabilities 
for those. It's a functionality residing in the CC today, but the general 
idea is to externalise that into a separate service that is reusable from 
both the cloud controller as well as Diego and potentially other 
consumers, and scalable independently from cc/diego. Read more in the 
document at 
https://docs.google.com/document/d/1kIjBuJJ0ZiJRPzMJW8dtce26jhAHbK7KotY9416YMEI/edit#

However, you are right that we probably should have a 'what is it' as part 
of the reamde.md under the repo - I will make sure we add that. 

Simon

**Comment by drnic** [comment]
Thanks for link to google doc. I missed the proposal email to cf-dev sorry.

On Sun, Feb 14, 2016 at 10:27 PM, Simon Moser notifications@github.com
wrote:

> Hey Nic,
> 
> the bits-service incubation has been already proposed some time ago via
> cf-dev. In short, the "bits service" is basically a service that will take
> bits (packages, droplets, etc) and provide upload/download capabilities
> for those. It's a functionality residing in the CC today, but the general
> idea is to externalise that into a separate service that is reusable from
> both the cloud controller as well as Diego and potentially other
> consumers, and scalable independently from cc/diego. Read more in the
> document at
> 
> https://docs.google.com/document/d/1kIjBuJJ0ZiJRPzMJW8dtce26jhAHbK7KotY9416YMEI/edit#
> 
> However, you are right that we probably should have a 'what is it' as part
> of the reamde.md under the repo - I will make sure we add that.
> 
> Simon
> 
> From: Dr Nic Williams notifications@github.com
> To: cloudfoundry-incubator/bits-service
> bits-service@noreply.github.com
> Date: 13/02/2016 23:22
> Subject: [bits-service] What is it? (#1)
> 
> Repo was mentioned in Feb 2016 CAB meeting notes but neither it nor this
> repo says what bits-service is.
> ?
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cloudfoundry-incubator/bits-service/issues/1#issuecomment-183881832
> .

## 

Dr Nic Williams
Stark & Wayne LLC - consultancy for Cloud Foundry users
http://drnicwilliams.com
http://starkandwayne.com
cell +1 (415) 860-2185
twitter @drnic
