### ISSUE TITLE
S3 compatible v2 signing support?

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bits-service#15]
Currently the BITS-Service only supports v4 signing for S3 compatible providers.
Any chance of adding a v2 signing option? 

Several other CF/BOSH related tools written in Go using the AWS SDK added v2 signing to accomodate S3 providers which only support that version.
(BOSH S3-Cli, Concourse S3 resource, etc.. for example: https://github.com/cloudfoundry/bosh-s3cli/blob/master/client/handlers.go#L66)

Without v2 signing it is unfortunately currently not possible for us to use the BITS-Service in CF. 😨

**Comment by eric-cartman** [comment]
@JamesClonk 
Thanks for your input. 
I would like to clarify some questions beforehand.
The first one would be:
Do you use AWS S3 Blobstores directly or some S3 compatible blobstore (i.e. IBM Cloud Object Storage)?
(notice - you have also been invited to the Cloud Foundry Slack / bits-service channel. Please let us know if you have any problems connecting to the channel)
Kind regards,
Tobias (bits-service team)

**Comment by petergtz** [comment]
Filling back some of the information we exchanged on Slack:

> jamesclonk [15 days ago]:
> we're using EMC Atmos, which is an s3 compatible provider (but only supports v2 signing unfortunately)
> as far as I know Atmos does not support v4 and/or has it planned. There's the successor product EMC ECS which supports v4, and eventually we will migrate to it, but it's currently a long term goal for us.
> It would've been great to have v2 support in the mean time, but I can understand your concerns. I'm aware that v2 is/will become deprecated.

We have added this story now on our backlog. More context can be found there. Find it here: https://www.pivotaltracker.com/story/show/161367982

**Comment by petergtz** [comment]
Hi @JamesClonk, this feature request is close to being released in the next Bits-Service version.

It has passed all our test environments. We've tested version 2 signatures against our AWS account. It would be cool if you could test against EMC Atmos once it's released.

For the long-term support, i.e. once AWS has turned of version 2 signatures, it would be cool to have an environment against which we could test this, such as Atmos. You don't happen to have a spare bucket you could share with us on a long-term basis, do you?

**Comment by JamesClonk** [comment]
@petergtz Unfortunately no, we don't have any public Atmos endpoints available. But I'll definitely test it as soon as it's released. (We want to put Bits-Service in production after all :grinning:)

**Comment by petergtz** [comment]
@JamesClonk OK, here you go: https://bosh.io/releases/github.com/cloudfoundry-incubator/bits-service-release?version=2.16.0.

[cf-deployment](https://github.com/cloudfoundry/cf-deployment/tree/develop)'s `develop` branch should soon point to this latest version. `master` will have it when they make their next release.

You can do the version bump in your environment even without waiting for cf-deployment. Bits-Service versions in the 2.x.x series are all backward's compatible. We do the same in IBM Cloud.

**Comment by JamesClonk** [comment]
@petergtz We just tested in our lab environment, seems to work great.
Thanks a lot! :+1:

**Comment by petergtz** [comment]
@JamesClonk Awesome! I'm closing this issue then. Please re-open, in case you do encounter issues.
