### ISSUE TITLE
Does keystone v3 support when using swift?

### ISSUE THREAD

**Issue by morika-t** [cloudfoundry-incubator/bits-service#16]
We experimented with the following configuration file

* keystone v2: OK
* keystone v3: Failure

Do you support keystone v3? Or are you planning to support it?
What kind of setting should I do in case of being supported?

* cf-deployments ops file: vars-use-bits-service-swift.yml

```
auth_url: "http://192.168.229.145:5000/v3/"

openstack_region: RegionOne
openstack_domain_id: default
openstack_username: bosh
openstack_password: dummypass
openstack_temp_url_key: dummykey

app_package_directory_key: cf-packages
buildpack_directory_key: cf-buildpacks
resource_directory_key: cf-resources
droplet_directory_key: cf-droplets
```

**Comment by petergtz** [comment]
Hi @morika-t,

In our pipelines we're testing against v3. Our config looks like this:

```
auth_url: "https://lon-identity.open.softlayer.com/v3"

region: london
domain_id: "c7b3b5e......297e4fdca"
username: "admin_b53810e.....34f5d"
password: "<redacted>"
account_meta_temp_url_key: <redacted>
```
It looks to me like your `domain_id` might not be correct. Is the config you provided working for you without Bits-Service?

Thanks.

**Comment by morika-t** [comment]
@petergtz 

Thank you for your reply.
I would like to change the setting and check the operation.

I will report it as soon as I know the result.

**Comment by morika-t** [comment]
@petergtz 

We succeeded under the following conditions where we additionally verified

* Using keystone v3
* domain_id is set to "default"
* Manually create bucket on Swift
