### ISSUE TITLE
Running out of disk space due to OCI registry artifacts

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry-incubator/bits-service#25]
We're running the OCI registry on the bit-service (for bosh-deployed Eirini & CF), and it seems that the tarballs served up by the registry (those in `<droplets-location>/sh/a2/` on the blobstore) are never getting deleted. For regular droplets, they are cleaned up if an app is deleted, but it seems that the corresponding tarball for the OCI registry is not removed. This is causing us to quickly run out of space on our blobstore VM. 

We see where the tarballs are being created: https://github.com/cloudfoundry-incubator/bits-service/blob/178b5be6fa8ae04c56fdf855177ded05f4cb286c/oci_registry/registry.go#L177 but we couldn't find where they get cleaned up.

We have a 100GB disk on a long-running CI environment, and we need to manually delete these tarballs every week or two to avoid running out of space.

Thanks,
Jen & @jspawar

**Comment by madamkiwi** [comment]
`2.27.0` seems to have resolved the issue. Thanks!

**Comment by petergtz** [comment]
@madamkiwi Glad to hear that! Closing.
